global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'airflow-webserver'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'celery-worker'
    static_configs:
      - targets: ['host.docker.internal:8001']
